force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UploaderCSVFileController.cls
public with sharing class UploaderCSVFileController {
    @AuraEnabled
    public static void saveFile(String base64Data, String typeOfObject) {
        List<Sensor__c> lstSensors = new List<Sensor__c>();
        List<Base_Station__c> lstBaseStations = new List<Base_Station__c>();
        List<List<String>> allFields = new List<List<String>>();
        String strCSVFile = JSON.deserializeUntyped(base64Data).toString();
        strCSVFile = strCSVFile.replaceAll(',"""', ',"DBLQT').replaceall('""",', 'DBLQT",');
        strCSVFile = strCSVFile.replaceAll('""', 'DBLQT');
        List<String> strCSVLines = new List<String>();
        strCSVLines = strCSVFile.split('\n');

       // Calling Parser Logic from the parseCSV Helper Class
        allFields = ParserCSV.getAllFields(strCSVLines);
       // Removed the first row at it contains the column name
        if (allFields.size() > 0) {
            allFields.remove(0);
        }        

        for (Integer i = 0; i < allFields.size(); i++) {           
            List<String> csvRecordData = allFields[i];
            if (typeOfObject == 'BaseStation') {
                Base_Station__c itemToInsert = new Base_Station__c(
                    Name = csvRecordData[0],
                    Status__c = csvRecordData[1],
                    External_Id__c = csvRecordData[2]
                );
                lstBaseStations.add(itemToInsert);

            } else if (typeOfObject == 'Sensor') {
                Sensor__c itemToInsert = new Sensor__c(
                    Sensor_model__c = csvRecordData[0],
                    Status__c = csvRecordData[1]
                );
                if (csvRecordData[2] != ' ') {
                    itemToInsert.Base_Station__r = new Base_Station__c(External_Id__c = csvRecordData[2]);
                }
                lstSensors.add(itemToInsert);
            }
        }
        if (!lstBaseStations.isEmpty()) {
            insert lstBaseStations;
        } else if (!lstSensors.isEmpty()) {
            insert lstSensors;
        }
    }
}