force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
@isTest
public with sharing class TestFactory {
    public static List<Base_Station__c> getBaseStations(Integer numRec, String name, String statusBS, Boolean doInsert){
        List<Base_Station__c> baseStations = new List<Base_Station__c>();
        for(Integer i = 0; i < numRec; i++){
            Base_Station__c bs = new Base_Station__c();
            bs.Name = name;
            bs.Status__c = statusBS;
            baseStations.add(bs);
        }
        if(doInsert){
            insert baseStations;
        }
        return baseStations;
    }
    public static List<Sensor__c> getSensorsWithoutBaseStation(Integer numRec, String model, String statusS, Boolean doInsert){
        List<Sensor__c> sensors = new List<Sensor__c>();
        for(Integer i = 0; i < numRec; i++){
            Sensor__c s = new Sensor__c();
            s.Sensor_model__c = model;
            s.Status__c = statusS;
            sensors.add(s);
        }
        if(doInsert){
            insert sensors;
        }
        return sensors;
    }
    public static List<Sensor__c> getSensorsWithBaseStation(Integer numRec, String name, String statusS, String nameBS, String statusBS, Boolean doInsert){
        Base_Station__c baseStation = getBaseStations(1, nameBS, statusBS, true).get(0);
        List<Sensor__c> sensors = getSensorsWithoutBaseStation(numRec, name, statusS, false);
        if (sensors.size() > 0){
            for(Sensor__c s : sensors){
                s.Status__c = baseStation.id;
                sensors.add(s);
            }
        }
        if(doInsert){
            insert sensors;
        }
        return sensors;
    }
}