force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BaseStationFlowTest.cls
@isTest
private with sharing class BaseStationFlowTest {
    @isTest
    static void changeStatusOfBaseStationOnInactive() {
        TestFactory.getSensorsWithBaseStation(5, 'model x2', 'Active', 'Parking place 1', 'Active', true);
        Base_Station__c changingBS = [SELECT Id,
                                             Name,
                                             Status__c 
                                      FROM Base_Station__c
                                      WHERE Status__c = 'Active' 
                                      LIMIT 1];
        List<Sensor__c> checkingSensors = [SELECT Id,
                                                  Name,
                                                  Base_Station__c,
                                                  Status__c,
                                                  Sensor_model__c
                                           FROM Sensor__c
                                           WHERE Base_Station__c = :changingBS.Id];
        System.debug('changingBS: ' + changingBS);
        System.debug('checkingSensors size: ' + checkingSensors.size());
        System.debug('checkingSensors.get(0): ' + checkingSensors.get(0));
        /*List<Account> accts = new List<Account>();
        Test.startTest();
        accts = [SELECT Id FROM Account];
        Test.stopTest();
        System.assert(accts.size() > 0, 'Was expecting to find at least one account');*/
    }
}