force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Base_Station_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Station_Name__c</fullName>
    <formula>Base_Station__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Station Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SensorConroller.cls
public with sharing class SensorConroller {
    @AuraEnabled(cacheable=true)
    public static List<Sensor__c> getSensorList() {
        return [SELECT Name,
                       Sensor_model__c,
                       Status__c,
                       Base_Station_Name__c
                FROM Sensor__c
                LIMIT 10000];
    }
    @AuraEnabled(cacheable=false)
    public static Boolean deleteSensor(String sensorId) {
        Sensor__c deletedRecord = [SELECT Id
                                   FROM Sensor__c
                                   WHERE Id = :sensorId
                                   LIMIT 1];
        Boolean answer = false;
        if (deletedRecord != null){
            try {
                System.debug('try');
                delete deletedRecord;
                answer = true;
            } catch (DmlException e) {
                System.debug('The following exception has occurred: ' + e.getMessage());
            }
        }
        return answer;
    }
    
}